name: Sugon Sync Repo

on:
  workflow_dispatch:
  push:
    branches: [ "sugon/aomp-dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: sync bitbucket
      run: git push --all ${{ secrets.BITBUCKET_URL }}
